import 'package:flutter/cupertino.dart';

class PsValueHolder {
  PsValueHolder(
      {@required this.loginUserId,
      @required this.loginUserName,
      @required this.locationId,
      @required this.locactionName,
      @required this.locationLat,
      @required this.locationLng,
      @required this.locationTownshipId,
      @required this.locationTownshipName,
      @required this.locationTownshipLat,
      @required this.locationTownshipLng,
      @required this.userIdToVerify,
      @required this.userNameToVerify,
      @required this.userEmailToVerify,
      @required this.userPasswordToVerify,
      @required this.deviceToken,
      @required this.isSubLocation,
      @required this.defaultCurrency,
      @required this.defaultCurrencyId,
      @required this.notiSetting,
      @required this.isCustomCamera,
      @required this.isToShowIntroSlider,
      @required this.overAllTaxLabel,
      @required this.overAllTaxValue,
      @required this.shippingTaxLabel,
      @required this.shopId,
      @required this.messenger,
      @required this.whatsApp,
      @required this.phone,
      @required this.shippingTaxValue,
      @required this.appInfoVersionNo,
      @required this.appInfoForceUpdate,
      @required this.appInfoForceUpdateTitle,
      @required this.appInfoForceUpdateMsg,
      @required this.startDate,
      @required this.endDate,
      @required this.paypalEnabled,
      @required this.stripeEnabled,
      @required this.codEnabled,
      @required this.bankEnabled,
      @required this.publishKey,
      @required this.shippingId,
      @required this.standardShippingEnable,
      @required this.zoneShippingEnable,
      @required this.noShippingEnable,
      @required this.detailOpenCount});
  String locationId;
  String locactionName;
  String locationLat;
  String locationLng;
  String locationTownshipId;
  String locationTownshipName;
  String locationTownshipLat;
  String locationTownshipLng;
  String loginUserId;
  String loginUserName;
  String userIdToVerify;
  String userNameToVerify;
  String userEmailToVerify;
  String userPasswordToVerify;
  String deviceToken;
  String isSubLocation;
  String defaultCurrency;
  String defaultCurrencyId;
  bool notiSetting;
  bool isCustomCamera;
  bool isToShowIntroSlider;
  String overAllTaxLabel;
  String overAllTaxValue;
  String shippingTaxLabel;
  String shopId;
  String messenger;
  String whatsApp;
  String phone;
  String shippingTaxValue;
  String appInfoVersionNo;
  bool appInfoForceUpdate;
  String appInfoForceUpdateTitle;
  String appInfoForceUpdateMsg;
  String startDate;
  String endDate;
  String paypalEnabled;
  String stripeEnabled;
  String codEnabled;
  String bankEnabled;
  String publishKey;
  String shippingId;
  String standardShippingEnable;
  String zoneShippingEnable;
  String noShippingEnable;
  int detailOpenCount;
}
